### ISSUE TITLE
Support for new versions of EC-Lab

### ISSUE THREAD

**Issue by erlendurj** [jmstrat/Echem.Data#1]
The read.echem() function does not support the latest version of EC-Lab data files. As per the error message from the function:
Error: Unrecognised version for data module: 3

A fix has been released for the Galvani python, showing that there's a small change in the binary file from newer version of EC-lab:
https://github.com/echemdata/galvani/pull/36/commits/72d79146e65b4f7fc598d78cb3df07824bd65b92

**Comment by jmstrat** [comment]
Don't have any data to test this on, but I've ported the python code over in #2.
