### ISSUE TITLE
Unmapped Column Types

### ISSUE THREAD

**Issue by cstjohn810** [jmstrat/Echem.Data#3]
### Prerequisites

* [x ] Are you running the latest version?
      (Use `remotes::update_packages()` to update packages)
* [x ] Can you reproduce the problem after restarting R with a clean environment?

### Describe the bug

When loading in Biologic .mpr files, I get a couple of unmapped columns - dQ.C and (Q-Qo).C

#### To Reproduce

```R
# Minimal code that demonstrates the problem
echem_file <- read.echem("file.mpr")
```

#### Expected behavior
Should read in files without warning

#### Operating environment

Copy and paste the output of running `sessionInfo()` here:
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

**Attachments**
NA

**Comment by jmstrat** [comment]
This is just the result of an overzealous warning, it means there isn't a normalised version of that column name that will be the same across every supported cycler type. As the warning is fairly meaningless, I've removed it as part of #4 – when this is merged the file will import without warnings.

Despite the warnings, the file itself should still be imported correctly. For example the following should still work:
```R
# import the data
echem_file <- read.echem("file.mpr")
# basic plot
plot(echem_file)
# look at the raw data
View(echem_file)
# etc.
```

If the data are not imported correctly imported, please attach an example file and let me know what's wrong.

**Comment by cstjohn810** [comment]
Great, thank you - that makes sense. The file import does look like it happened correctly but I was thinking the warning meant those columns wouldn't be mapped. Thank you for this package by the way - it saved me tons of time trying to figure out the binary import myself.

**Comment by jmstrat** [comment]
Ok great, in which case I'll merge #4 which will close this issue
